### ISSUE TITLE
Test fails on 2nd run

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/rasrm-acceptance-tests#134]
This failure occurs when the test-suite is run twice:

Failing scenarios:
 acceptance_tests/features/change_response_status.feature:19  Internal user can change the response status to No Longer Required

Tests should be idempotent; we shouldn't get different results across multiple runs. The status of this DB should be reset between test runs.

**Comment by JamesGardiner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single test failing on second run](https://trello.com/c/PIku2o9u/107-single-test-failing-on-second-run)

**Comment by benjefferies** [comment]
I've managed to build two runs of the acceptance tests by running `make wait_for_services setup acceptance_tests`
