### ISSUE TITLE
Cannot run the tests twice in a row without clearing down the containers

### ISSUE THREAD

**Issue by benjefferies** [ONSdigital/rasrm-acceptance-tests#69]
The tests below fail if you run them twice in a row.
```
Failing scenarios:
  acceptance_tests/features/set_ready_for_live.feature:11  Once the user is happy with the contents of the collection exercise, they are able to set the collection exercise as 'Ready for Live'
  acceptance_tests/features/set_ready_for_live.feature:19  On choosing to set the collection exercise as 'Ready for Live', the user is asked to confirm before continuing and given the option to cancel
  acceptance_tests/features/set_ready_for_live.feature:26  The user is to be informed if the system is processing the collection exercise
  acceptance_tests/features/set_ready_for_live.feature:33  The user is able to refresh the page at any point
  acceptance_tests/features/set_ready_for_live.feature:41  When the user sets the collection exercise as 'Ready for Live' no further changes can be made to the collection exercise
```

We currently put the database back into a "known" state when starting the tests which doesn't look to be happening for these tests.

Long term we should look at writing the tests such that we don't need to reset data and the tests will generate new data each time

**Comment by jcox-dev** [comment]
Somewhat expected, known (and coincidentally overlooked) as "un-executing" a collection exercise was described as non-trivial. 

I'm actually surprised it's only these tests that fail when running them all a second time(!).

**Comment by madeye-matt** [comment]
Is there an easy way to clear out the database?  Can't we do this automatically as part of the tests?Rebuilding the docker container does it, but that means you have to restart all the services.

**Comment by madeye-matt** [comment]
@benjefferies @jcox-dev I think I have a fix for this - I am going to add a target 'reset_database' to the acceptance test Makefile to clear out the database, we can then work out how best to incorporate it.  Once I'm done I'll raise a PR (might be tomorrow, just testing it now)

**Comment by jcox-dev** [comment]
Somewhat resolved by rasrm-acceptance-tests/reset_database.py
